apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: distributed-unique-id-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: unique-id
    spec:
      containers:
      - name: unique-id
        image: exifguy/uniqueid:v1
        env:
        - name: UNIQUE_ID_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8080